const defaultParams = [
  {
    name: 'maxRetries',
    value: 3,
    type: 'select',
    optionList: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    name: 'maxRepeats',
    value: 3,
    type: 'select',
    optionList: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    name: 'lang',
    value: 'bcxEn',
  },
  {
    name: 'currency',
    value: 'SAR',
  },
  {
    name: 'terminator',
    value: '#',
    type: 'select',
    optionList: [
      'X',
      '#',
      '*',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
    ],
  },
  {name: 'firstTimeout', value: 10},
  {name: 'interTimeout', value: 5},
  {name: 'menuTimeout', value: 5},
  {name: 'maxCallTime', value: 3600},
  {
    name: 'invalidAction',
    type: 'select',
    optionList: ['Disconnect', 'Transfer'],
    value: 'Disconnect',
  },
  {
    name: 'timeoutAction',
    type: 'select',
    optionList: ['Disconnect', 'Transfer'],
    value: 'Disconnect',
  },
  {
    name: 'confirmOption',
    value: 1,
    type: 'select',
    optionList: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    name: 'cancelOption',
    value: 2,
    type: 'select',
    optionList: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {name: 'invalidPrompt', value: 'std-invalid'},
  {name: 'timeoutPrompt', value: 'std-timeout'},
  {name: 'cancelPrompt', value: 'std-cancel'},
  {
    name: 'goodbyeMessage',
    value: 'std-goodbye',
  },
  {
    name: 'terminateMessage',
    value: 'std-terminate',
  },
  {name: 'transferPrompt', value: 'std-to-transfer'},
  {name: 'disconnectPrompt', value: 'std-to-disconnect'},
  {name: 'previousMenuPrompt', value: 'std-to-previous-menu'},
  {
    name: 'mainMenuPrompt',
    value: 'std-to-main-menu',
  },

  {
    name: 'repeatInfoPrompt',
    value: 'std-to-repeat',
  },
  {
    name: 'confirmPrompt',
    value: 'std-confirm',
  },
  {
    name: 'hotkeyMainMenu',
    value: 'X',
    type: 'select',
    optionList: [
      'X',
      '#',
      '*',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
    ],
  },
  {
    name: 'hotkeyPreviousMenu',
    value: 'X',
    type: 'select',
    optionList: [
      'X',
      '#',
      '*',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
    ],
  },
  {
    name: 'hotkeyTransfer',
    value: 'X',
    type: 'select',
    optionList: [
      'X',
      '#',
      '*',
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
    ],
  },
  {
    name: 'transferPoint',
    value: '',
  },
  {
    name: 'invalidTransferPoint',
    value: '',
  },
  {
    name: 'timeoutTransferPoint',
    value: '',
  },
  {
    name: 'allowedDigits',
    value: '1234567890',
  },
  {
    name: 'logDB',
    value: false,
    type: 'switch',
  },
];

export default defaultParams;
